apiVersion: v1
kind: Service
Metadata:
  name: rushi-app-svc
  labels:
    app: rushi-app
spec:
  type: NodePort
  selector:
    app: rushi_app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30883